apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i4i1c659q-dotnet-basic
  janus-idp.io/tekton: i4i1c659q-dotnet-basic
  backstage.io/kubernetes-id: i4i1c659q-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i4i1c659q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
